name: Actualizador Diario de Presas CONAGUA

on:
  schedule:
    # Se ejecuta todos los días a las 06:00 AM y 06:00 PM (hora UTC)
    - cron: '0 6,18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Ejecutar script de actualización de presas
        run: node scripts/actualizarPresas.js

      - name: Hacer commit y push automático de presas_sinaloa.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-actualizacion de datos de presas Sinaloa
          file_pattern: 'presas_sinaloa.json'
